name: "Lighthouse Badger"

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as Secrets (env) for not manually triggered workflows
env:
  URLS: https://alshedivat.github.io/al-folio/
  # If any of the following env is blank, a default value is used instead
  REPO_BRANCH: "${{ github.repository }} master" # target repository & branch e.g. 'dummy/mytargetrepo main'
  MOBILE_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2"
  DESKTOP_LIGHTHOUSE_PARAMS: "--only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1"

# TRIGGERS
on:
  page_build:
  schedule: # Check your schedule here => https://crontab.guru/
    - cron: '55 23 * * 0' # e.g. every Sunday at 23:55
  workflow_dispatch:

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  lighthouse-badger-easy:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # 增加超时时间，避免复杂任务超时
    steps:
      # Step 1: 解析 REPOSITORY 和 BRANCH
      - name: Preparatory Tasks
        run: |
          REPOSITORY=$(echo "${{ env.REPO_BRANCH }}" | awk '{print $1}')
          BRANCH=$(echo "${{ env.REPO_BRANCH }}" | awk '{print $2}')
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        env:
          REPO_BRANCH: ${{ env.REPO_BRANCH }}

      # Step 2: 检出目标仓库代码
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY }}
          token: ${{ secrets.LIGHTHOUSE_BADGER_TOKEN }}
          ref: ${{ env.BRANCH }}

      # Step 3: 检出 Lighthouse Badges 仓库
      - name: Checkout Lighthouse Badges Repository
        uses: actions/checkout@v4
        with:
          repository: "myactionway/lighthouse-badges"
          path: temp_lighthouse_badges_nested

      # Step 4: 运行 Lighthouse-Badger Action
      - name: Run Lighthouse-Badger
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}

